### ISSUE TITLE
After update oVirt to 4.2.5 backups not complited.

### ISSUE THREAD

**Issue by dark4rest** [bacchus-ng/bacchus#30]
After update oVirt to 4.2.5 backups not complited. Snapshots created, but clonning not started.

**Comment by Sennar81** [comment]
I've the same problem. The worker.log say:
Task manager.tasks.backup_vm[d360f381-ad43-4bce-86a9-20c85434c09c] raised unexpected: Error('Fault reason is "Operation Failed". Fault detail is "[Cannot add VM. Snapshot is currently being created for VM XXXXXXXX.]". HTTP response code is 409.',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/bacchus/manager/tasks.py", line 24, in backup_vm
    return VMTools.backup_vm(rhevmname,vmname)
  File "/opt/bacchus/manager/vmtools.py", line 262, in backup_vm
    cloned_vm = vms_service.add( vm=types.Vm(name=snapshot_name, cluster=types.Cluster(id=vm.cluster.id), snapshots=[types.Snapshot(id=snap.id)] ))
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 33829, in add
    return self._internal_add(vm, headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 232, in _internal_add
    return future.wait() if wait else future
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 55, in wait
    return self._code(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 229, in callback
    self._check_fault(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 132, in _check_fault
    self._raise_error(response, body)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 118, in _raise_error
    raise error
Error: Fault reason is "Operation Failed". Fault detail is "[Cannot add VM. Snapshot is currently being created for VM XXXXXXXX.]". HTTP response code is 409

**Comment by hudecof** [comment]
I did not check logs, but after upgrade from `4.2.3` to `4.2.5` the backup is not working.
The snapshot is created, but that's all.

**Comment by hudecof** [comment]
the same error
```
[2018-08-20 15:57:36,620: ERROR/ForkPoolWorker-14] Task manager.tasks.backup_vm[0654c3d8-8d5f-4675-bd37-4f799142f68c] raised unexpected: Error('Fault reason is "Operation Failed". Fault detail is "[Cannot add VM. Snapshot is currently being created for VM dipbfwcctv01.]". HTTP response code is 409.',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/bacchus/manager/tasks.py", line 24, in backup_vm
    return VMTools.backup_vm(rhevmname,vmname)
  File "/opt/bacchus/manager/vmtools.py", line 262, in backup_vm
    cloned_vm = vms_service.add( vm=types.Vm(name=snapshot_name, cluster=types.Cluster(id=vm.cluster.id), snapshots=[types.Snapshot(id=snap.id)] ))
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 34491, in add
    self._check_fault(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 98, in _check_fault
    Service._raise_error(response, fault)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 71, in _raise_error
    raise Error(msg)
Error: Fault reason is "Operation Failed". Fault detail is "[Cannot add VM. Snapshot is currently being created for VM dipbfwcctv01.]". HTTP response code is 409.
```

**Comment by hudecof** [comment]
it seems to be oVirt bug

**Comment by Sennar81** [comment]
I have created a script that uses ovirt's api and it works without problems. Maybe the problem is the status of the disks.

**Comment by hudecof** [comment]
@Sennar81 please could you share it? My testing script is https://tools.apps.hudecof.net/paste/view/0319f4f1

**Comment by hudecof** [comment]
after short discussion in ovirt mailing list I created bug report

https://bugzilla.redhat.com/show_bug.cgi?id=1620087

**Comment by Sennar81** [comment]
My script is:
-------------------------------------------------------
#!/usr/bin/env python
# -*- coding: utf-8 -*-


import logging
import time

import ovirtsdk4 as sdk
import ovirtsdk4.types as types
from datetime import datetime, timedelta

logging.basicConfig(level=logging.DEBUG, filename='example.log')

vmname = 'VMxxxx'


# CREAZIONE CONNESSIONE ALLE API oVirt
connection = sdk.Connection(
    url='https://ovirtengine.csaricerche.internal/ovirt-engine/api',
    username='admin@internal',
    password='xxxxxx',
    insecure=True,
    debug=True,
    log=logging.getLogger(),
)

#CONNECT OVIRT SERVICE
system_service = connection.system_service()

# FIND VM
vms_service = system_service.vms_service()
try:
	vm = vms_service.list(search='name='+vmname)[0]
except Exception as e:
	connection.close()		
	print "VM not found!"
	exit(1)
	
# CONNECT TO VM's SERVICE
vm_service = vms_service.vm_service(vm.id)

snapshot_name = "csabackup_"+vmname+"_"+str(datetime.fromtimestamp(time.time()).strftime('%Y%m%d_%H%M%S'))


# CONNECT SERVICE SNAPSHOT
snapshots_service = vm_service.snapshots_service()

try:
	# CREATE SNAPSHOT
	snap = snapshots_service.add(
		types.Snapshot(description=snapshot_name, persist_memorystate=False,),
	)
	
except Exception as e:
	print "Snapshot creation failed on [ "+vmname +" ] with the following error  \n"+str(e)+"\n"
	connection.close()			
	exit(1)

# CONNECT TO SERVICE OF THE SNAPHOTS CREATED
snap_service = snapshots_service.snapshot_service(snap.id)
		
while snap.snapshot_status != types.SnapshotStatus.OK:
	time.sleep(6)
	snap = snapshots_service.snapshot_service(snap.id).get()
	

#VERIFY AND WAITING STATUS DISK OF THE ORIGINAL VM
disk_attachments_service = vms_service.vm_service(vm.id).disk_attachments_service()
disk_attachments = disk_attachments_service.list()

for disk_attachment in disk_attachments:
	disk_attachment_service = disk_attachments_service.attachment_service(disk_attachment.id)
	while True:
		time.sleep(5)
		disk_attachment = disk_attachment_service.get()
		if disk_attachment.active == True:
			break


try:
	# CREATE CLONE VM
	cloned_vm = vms_service.add(
		vm=types.Vm(
			name=snapshot_name,
			snapshots=[
				types.Snapshot(
					id=snap.id
				)
			],
			cluster=types.Cluster(
				id=vm.cluster.id
			)
		)
	)
except Exception as e:
	print "VM creation from Snapshots failed on [ "+vmname +" ] with the following error  \n"+str(e)+"\n"
	connection.close()			
	exit(1)

# CONNECT TO TEMPORARY VM SERVICE
cloned_vm_service = vms_service.vm_service(cloned_vm.id)

# CHECK STATUS TEMPORARY VM
while True:
    time.sleep(5)
    cloned_vm = cloned_vm_service.get()
    if cloned_vm.status == types.VmStatus.DOWN:
        break

# DELETE SNAPHOTS
snap_service.remove()

# FIND ID DOMAIN EXPORT
sds_service = connection.system_service().storage_domains_service()
sds = sds_service.list()
i = 0
while ((sds[i].type.value != 'export')&(i<len(sds))):
	i = i +1

if (i<len(sds)):
	export_domain=sds[i]
else:		
	export_domain=None

# EXPORT TEMPORARY VM 
exported_vm = cloned_vm_service.export(storage_domain=types.StorageDomain(name=export_domain.name))
		
while True:
	time.sleep(2)
	cloned_vm = cloned_vm_service.get()
	if cloned_vm.status == types.VmStatus.DOWN:
		break

# DELETE TEMPORARY VM
cloned_vm_service.remove()

# DISCONNCT oVirt API
connection.close()

-------------------------------------------------------
Excuse me for my english

**Comment by hudecof** [comment]
your code do not work for me. I have to ched=ck the disk status, so the disk checking part looks like

```
disk_attachments_service = vms_service.vm_service(vm.id).disk_attachments_service()
disk_attachments = disk_attachments_service.list()
for disk_attachment in disk_attachments:
    disk = connection.follow_link(disk_attachment.disk)
    print("DISK %s: %s" % (disk.name, disk.status))
    while disk.status != types.DiskStatus.OK:
        time.sleep(1)
        disk = connection.follow_link(disk_attachment.disk)
        print("DISK %s: %s" % (disk.name, disk.status))
```
