### ISSUE TITLE
Ansible Installation - flower setup error

### ISSUE THREAD

**Issue by skunkr** [bacchus-ng/bacchus#48]
Hi,
I am encountering this error,  during a fresh install:

TASK [Install Flower] ***********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip2 install flower", "msg": "stdout: Collecting flower\n  Downloading https://files.pythonhosted.org/packages/36/15/ed670b1f1fe14727f1564c9d98d7a917352ce8a0d88e87256be3c1e1190e/flower-0.9.3.tar.gz (1.3MB)\n    Complete output from command python setup.py egg_info:\n    error in flower setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers\n    \n    ----------------------------------------\n\n:stderr: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.\nCommand \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-install-loqQjG/flower/\n"}
        to retry, use: --limit @/root/installer.retry
*******************************************************************************************
Any thoughts or suggestions ?
Thank you very much !

**Comment by skunkr** [comment]
It seems the performing "pip install setuptools -U"  prior running th eplaybbok,  did the trick.

**Comment by armagankaratosun** [comment]
Very glad to hear that. I am closing this issue because it is resolved right now, but you can always open a new issue if you encounter an error.
