### ISSUE TITLE
Installation does not finnish - Centos 7

### ISSUE THREAD

**Issue by skunkr** [bacchus-ng/bacchus#49]
Hi,
Fresh install, it throws the folowing error regarding django,  even though i have issued "pip --upgrade django" before running the playbook. 
I had to upgrade celery accordingly toissue #47 :

TASK [Open Bacchus preflight check] *********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["python", "manage.py", "check"], "delta": "0:00:01.092414", "end": "2019-04-13 10:48:57.186008", "msg": "non-zero return code", "rc": 1, "start": "2019-04-13 10:48:56.093594", "stderr": "Traceback (most recent call last):\n  File \"manage.py\", line 22, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/lib64/python2.7/site-packages/django/core/management/__init__.py\", line 367, in execute_from_command_line\n    utility.execute()\n  File \"/usr/lib64/python2.7/site-packages/django/core/management/__init__.py\", line 316, in execute\n    settings.INSTALLED_APPS\n  File \"/usr/lib64/python2.7/site-packages/django/conf/__init__.py\", line 53, in __getattr__\n    self._setup(name)\n  File \"/usr/lib64/python2.7/site-packages/django/conf/__init__.py\", line 41, in _setup\n    self._wrapped = Settings(settings_module)\n  File \"/usr/lib64/python2.7/site-packages/django/conf/__init__.py\", line 97, in __init__\n    mod = importlib.import_module(self.SETTINGS_MODULE)\n  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/opt/bacchus/bacchus/__init__.py\", line 2, in <module>\n    from .celery import app as celery_app\n  File \"/opt/bacchus/bacchus/celery.py\", line 8, in <module>\n    app = Celery('bacchus')\n  File \"/usr/lib/python2.7/site-packages/celery/app/base.py\", line 286, in __init__\n    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]\n  File \"/usr/lib/python2.7/site-packages/celery/fixups/django.py\", line 46, in fixup\n    _verify_django_version(django)\n  File \"/usr/lib/python2.7/site-packages/celery/fixups/django.py\", line 34, in _verify_django_version\n    raise ImproperlyConfigured('Celery 4.x requires Django 1.11 or later.')\ncelery.exceptions.ImproperlyConfigured: Celery 4.x requires Django 1.11 or later.", "stderr_lines": ["Traceback (most recent call last):", "  File \"manage.py\", line 22, in <module>", "    execute_from_command_line(sys.argv)", "  File \"/usr/lib64/python2.7/site-packages/django/core/management/__init__.py\", line 367, in execute_from_command_line", "    utility.execute()", "  File \"/usr/lib64/python2.7/site-packages/django/core/management/__init__.py\", line 316, in execute", "    settings.INSTALLED_APPS", "  File \"/usr/lib64/python2.7/site-packages/django/conf/__init__.py\", line 53, in __getattr__", "    self._setup(name)", "  File \"/usr/lib64/python2.7/site-packages/django/conf/__init__.py\", line 41, in _setup", "    self._wrapped = Settings(settings_module)", "  File \"/usr/lib64/python2.7/site-packages/django/conf/__init__.py\", line 97, in __init__", "    mod = importlib.import_module(self.SETTINGS_MODULE)", "  File \"/usr/lib64/python2.7/importlib/__init__.py\", line 37, in import_module", "    __import__(name)", "  File \"/opt/bacchus/bacchus/__init__.py\", line 2, in <module>", "    from .celery import app as celery_app", "  File \"/opt/bacchus/bacchus/celery.py\", line 8, in <module>", "    app = Celery('bacchus')", "  File \"/usr/lib/python2.7/site-packages/celery/app/base.py\", line 286, in __init__", "    self._fixups = [symbol_by_name(fixup)(self) for fixup in self.fixups]", "  File \"/usr/lib/python2.7/site-packages/celery/fixups/django.py\", line 46, in fixup", "    _verify_django_version(django)", "  File \"/usr/lib/python2.7/site-packages/celery/fixups/django.py\", line 34, in _verify_django_version", "    raise ImproperlyConfigured('Celery 4.x requires Django 1.11 or later.')", "celery.exceptions.ImproperlyConfigured: Celery 4.x requires Django 1.11 or later."], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/bacchus/installer.retry

Any thoughts ?

Thank you !

**Comment by armagankaratosun** [comment]
Hi, please use our new installer, https://github.com/bacchus-ng/bacchus-ansible

**Comment by armagankaratosun** [comment]
If you get an error while installing flower, just run pip install setuptools -U and re-run the ansible job.

**Comment by skunkr** [comment]
Thank you,  but i do not understand what is the installation playbook in this repo.
Should i just run "ansible-playbook /tasks/main.yaml"  ?

**Comment by armagankaratosun** [comment]
nah, 

-  clone the repo with `git clone https://github.com/bacchus-ng/bacchus-ansible.git` 
-  create the playbook outside of the bacchus-ansible file ( example  main.yml file can be found in the README)
- run with `ansible-playbook main.yml`

check out my example setup;

```
[root@poetic-shepherd ~]# ls
bacchus-ansible  main.yml

[root@poetic-shepherd ~]# tree
.
|-- bacchus-ansible
|   |-- README.md
|   |-- meta
|   |   `-- main.yml
|   |-- tasks
|   |   |-- CentOS
|   |   |   `-- main.yml
|   |   |-- RedHat -> CentOS/
|   |   |-- Ubuntu
|   |   |   `-- main.yml
|   |   |-- common.yml
|   |   `-- main.yml
|   `-- vars
|       `-- main.yml
`-- main.yml
```
and my main.yml file;

```
- name: Install => Open Bacchus
  hosts: localhost
  gather_facts: true
  become: true

  roles:
   - bacchus-ansible
```

**Comment by skunkr** [comment]
Thank you,  it worked ! 
I just needed to disable Selinux,  otherwise nginx won't be able to listen 8081.
